### ISSUE TITLE
Stateful services?

### ISSUE THREAD

**Issue by trabianmatt** [trabian/clojure-elixir-comparison#1]
@jimmyhmiller can you expand on your comment that Elixir "encourages stateful services"? I've not found that to be the case but want to understand that perspective.

**Comment by jimmyhmiller** [comment]
Processes are the fundamental abstraction behind elixir. A large portion of what makes processes so powerful is their ability to hold state. This is why otp is such a great fit for telecom systems, video game backends, etc, each process holds a persistent (stateful) connection. 

This is also why hot deploys are so important. When you have stateful processes, you have to hot deploy or else you lose that state.

**Comment by trabianmatt** [comment]
Gotcha - I understand the ability for processes to hold state but didn't feel encouraged to do so. It's an available tool but the developer still decides whether it makes sense to do so. Any persistent state went into a database or into [ETS](http://erlang.org/doc/man/ets.html).

**Comment by jimmyhmiller** [comment]
[ETS](http://elixir-lang.org/getting-started/mix-otp/ets.html) is a perfect example of stateful services. ETS is in memory.

Stateful processes is elixir's biggest benefit. They enable speed and scalability that is incredibly impressive.

What do you see as Elixir's biggest benefit if not stateful processes?

**Comment by trabianmatt** [comment]
Resilience and performance were the big ones for me. Knowing that it handled stateful processes when needed gave me confidence we could use it when needed. Generally I like the concurrency model and OTP as a means of confidently growing a system beyond a single machine.

**Comment by jimmyhmiller** [comment]
>Resilience and performance were the big ones for me.

These are definitely strong areas for elixir. But I think we should try our best to compare them to Clojure rather than just make generalizations. What sorts of failures is Elixir resilient to that Clojure is not? Network partitions? Crashing VMs?

As for performance, what is the gap between Elixir and Clojure? With the caveat that benchmarks are the worst, [techempower](https://www.techempower.com/benchmarks/#section=data-r13&hw=cl&test=json&l=4dblrv) shows Clojure and Elixir all inside the same order of magnitude on performance. 

>Knowing that it handled stateful processes when needed gave me confidence we could use it when needed.

Clojure handles stateful processes too. You can make them however you'd like including using pulsar for otp style handling. 

>Generally I like the concurrency model and OTP as a means of confidently growing a system beyond a single machine.

See, I don't see this quite as positively as I know you do. Clojure can definitely grow beyond a single machine. In fact, any language can if you write stateless services. Stateless services are infinitely horizontally scalable (your bottle neck will be the database, something amazon has taken care of for us).

What elixir is offering that is unique is the means to scale stateful services across nodes without an external tool. This is a really amazing power but definitely comes with complications. When you have multiple processes communicating in an asynchronous fashion, you have to worry about deadlocks, race conditions, and process starvation.

Yes, it is amazing that Elixir (Erlang) makes all this work and makes it work very well, but these are all problems that can be avoided by making stateless services. It is just like how multi-threading can be solved by using FP instead of OOP.

All that being said, Elixir is a fantastic language. If we ever find ourselves building a distributed queue, distributed database, a chat system, a video backend, it would be my top choice.
